apiVersion: v1
kind: Service
metadata:
  name: flight-price-prediction-service
spec:
  selector:
    app: flight-price-prediction
  ports:
    - protocol: TCP
      port: 80  # External Port (Accessible from Browser)
      targetPort: 5000  # Matches Flask Container Port
  type: NodePort  # Use NodePort if deploying locally with Minikube
